// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeerEvalAppAPI.Data;

#nullable disable

namespace PeerEvalAppAPI.Migrations
{
    [DbContext(typeof(PeerEvalAppDbContext))]
    partial class PeerEvalAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeerEvalAppAPI.Data.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EvaluateeUserId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationCycleId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluatorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluateeUserId");

                    b.HasIndex("EvaluationCycleId");

                    b.HasIndex("EvaluatorUserId");

                    b.ToTable("Evaluations", (string)null);
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.EvaluationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("QuestionId");

                    b.ToTable("EvaluationAnswers", (string)null);
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.EvaluationCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("EvaluationCycles", (string)null);
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupName = "Admins",
                            InsertedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 627, DateTimeKind.Local).AddTicks(8714),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(8802),
                            Text = "Self-Confidence"
                        },
                        new
                        {
                            Id = 2,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9080),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9086),
                            Text = "Dedication"
                        },
                        new
                        {
                            Id = 3,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9088),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9090),
                            Text = "Job Knowledge"
                        },
                        new
                        {
                            Id = 4,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9092),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9093),
                            Text = "Quality and Accuracy of Work"
                        },
                        new
                        {
                            Id = 5,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9096),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9097),
                            Text = "Ability to Meet Deadlines"
                        },
                        new
                        {
                            Id = 6,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9099),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9100),
                            Text = "Independence"
                        },
                        new
                        {
                            Id = 7,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9102),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9103),
                            Text = "Commitment"
                        },
                        new
                        {
                            Id = 8,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9105),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9106),
                            Text = "Attention to Detail"
                        },
                        new
                        {
                            Id = 9,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9108),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9110),
                            Text = "Ability to Work with Others"
                        },
                        new
                        {
                            Id = 10,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9112),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9113),
                            Text = "Communication Skills"
                        },
                        new
                        {
                            Id = 11,
                            InsertedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9115),
                            ModifiedAt = new DateTime(2025, 1, 26, 23, 42, 39, 642, DateTimeKind.Local).AddTicks(9116),
                            Text = "Performs Assigned Duties Under Pressure"
                        });
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Evaluation", b =>
                {
                    b.HasOne("PeerEvalAppAPI.Data.User", "EvaluateeUser")
                        .WithMany("EvaluationsReceived")
                        .HasForeignKey("EvaluateeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerEvalAppAPI.Data.EvaluationCycle", "EvaluationCycle")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluationCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerEvalAppAPI.Data.User", "EvaluatorUser")
                        .WithMany("EvaluationsMade")
                        .HasForeignKey("EvaluatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluateeUser");

                    b.Navigation("EvaluationCycle");

                    b.Navigation("EvaluatorUser");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.EvaluationAnswer", b =>
                {
                    b.HasOne("PeerEvalAppAPI.Data.Evaluation", "Evaluation")
                        .WithMany("Answers")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeerEvalAppAPI.Data.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.User", b =>
                {
                    b.HasOne("PeerEvalAppAPI.Data.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PeerEvalAppAPI.Data.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Evaluation", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.EvaluationCycle", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PeerEvalAppAPI.Data.User", b =>
                {
                    b.Navigation("EvaluationsMade");

                    b.Navigation("EvaluationsReceived");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
